### ISSUE TITLE
Create design guide lines page.

### ISSUE THREAD

**Issue by dlabaj** [patternfly/react-user-feedback#21]
Design guide lines need to be added for this extension so it can appear on the patternfly.org site.  Currently we have the following [document](https://docs.google.com/document/d/1YJDtqX3tkckYnSY60d4bnNoVqx2wn8BardqjX4uoyVc/edit#heading=h.q7nw7wd501rx) that describes how the extension works, however it may need some additions to get the design guide line page created for the site.

**Comment by mmenestr** [comment]
patternfly-org issue created: https://github.com/patternfly/patternfly-org/issues/3440

**Comment by UtpalaJ** [comment]
Hi, Please assign this to me if you're accepting contributions on this issue, I'd like to help.

**Comment by jessiehuff** [comment]
Initial documentation added: https://github.com/patternfly/react-user-feedback/pull/49

**Comment by dlabaj** [comment]
Documentation has been completed.  closing this issue.
