### ISSUE TITLE
Create a patternfly version of the feedback image

### ISSUE THREAD

**Issue by dlabaj** [patternfly/react-user-feedback#22]
Currently we do not have a patternfly version of the [feedback image.](https://github.com/patternfly/react-user-feedback/blob/main/packages/module/src/images/feedback_illo.svg)  We should create one to replace the non patternfly version we currently have.

**Comment by maryshak1996** [comment]
Here is an image that is very similar to the downstream version but uses PF colors and the same Undraw.io illustration library elements as the PF community page. 

**Here is a mockup of it in context**
![feedback-modal_upstream-style-mockup](https://user-images.githubusercontent.com/19824574/224762245-81b8fe57-ab70-4ce1-a8d5-76790546fefc.png)

**Here is the SVG source file**
![feedback-modal_upstream-style](https://user-images.githubusercontent.com/19824574/224762368-ae9f7540-903c-4240-9e9f-a298a52c7157.svg)

**If needed, here is a PNG source**
![feedback-modal_upstream-style](https://user-images.githubusercontent.com/19824574/224762411-37910beb-0809-4e55-a921-079827cd5506.png)
