### ISSUE TITLE
Integrate feedback with on prem products

### ISSUE THREAD

**Issue by dlabaj** [patternfly/react-user-feedback#7]
Integrate react feedback with on prem products.  The user feedback should be back ported / integrated with console dot code.  There should be the ability to turn off sections when back porting (e.g. support)

**Comment by jessiehuff** [comment]
OpenShift PR: https://github.com/openshift/console/pull/12611

**Comment by jessiehuff** [comment]
OpenShift PR merged, PR created to backport user feedback to previous version: https://github.com/openshift/console/pull/12637

**Comment by jessiehuff** [comment]
OpenShift has decided not to backport user feedback so we can close this issue.
